name: Remove snapshot branch

on:
  pull_request_target:
    types:
      - closed

jobs:
  delete-pr-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.sender.login != 'dependabot[bot]'
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Remove snapshot branch
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: git push origin -d "snapshots/$PR_NUMBER" || true
